# 数据集路径，修改为个人存放数据集的路径下
path: D:\BiShe\data\yolo


# 训练我提供的数据集，以下内容不需要改动；训练自己的数据集，根据个人情况修改
train:
  - train
val:
  - val
test:
  - test

# 类别名称，不支持中文
names:
  [ 'dandelion', 'TrunpetflowerSeed', 'black_tremella', 'Oyster', 'yiren', 'red_dates', 'AntelopeHorn', 'yam', 'BupleurumChinese', 'muli', 'ginger', 'RedLyciiFructus', 'Garlic', 'Shanzha', 'tainma', 'YellowChrysanthemumFlower', 'bajiao', 'purple_Lingzhi', 'BlackLyciiFructus', 'redyiren', 'BupleurumScorzonerifolium', 'haima', 'Sanqi', 'white_ginseng', 'ChuanXiong', 'Zhizi', 'Chantui', 'TrionycisCarapax', 'pangdahai', 'WhiteChrysanthemumFlower', 'SemenArecae', 'Shanyinhua', 'red_ginseng', 'red_Lingzhi', 'AngelicaDahurica', 'white_Tremella', 'lotusseeds', 'black_dates' ]





